<?php
/** @var Meanbee_Shippingrules_Helper_Data $helper */
$helper = Mage::helper('meanbee_shippingrules');

/** @var Meanbee_Shippingrules_Helper_Config $config */
$config = Mage::helper('meanbee_shippingrules/config');
?>
<ul class="messages">
    <li class="notice-msg">
        <p><?php echo $helper->__('Rules from a previous version of Shipping Rules have been detected but are not ready for migration. See our <a href="%s" target="_blank">migration guide</a> for details.', $config->getDocumentationURL()) ?></p>
    </li>
</ul>