<?php
/** @var Meanbee_Shippingrules_Helper_Data $helper */
$helper = Mage::helper('meanbee_shippingrules');

/** @var Meanbee_Shippingrules_Helper_Config $config */
$config = Mage::helper('meanbee_shippingrules/config');

/** @var Meanbee_Shippingrules_Helper_Migration $migration */
$migration = Mage::helper('meanbee_shippingrules/migration');
?>
<ul class="messages">
    <li class="notice-msg">
        <form ction="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/shippingrules/migrate') ?>" method="post">
        <p><?php echo $helper->__('Rules from a previous version of Shipping Rules have been detected, however the following rules are not ready for migration:'); ?></p>
        <?php $references = $migration->getReferencesByMigrationStatus(); ?>
        <ul>
            <?php foreach($references[Meanbee_Shippingrules_Helper_Migration::MIGRATION_MALFORMED] as $reference): ?>
                <li><?php echo $reference ?></li>
            <?php endforeach; ?>
        </ul>
        <p><?php echo $helper->__('Would you like the migratable rules to be migrated anyway? See our <a href="%s" target="_blank">migration guide</a> for details.', $config->getDocumentationURL()) ?></p>
        <button title="<?php echo $helper->__('Yes') ?>" type="submit" name="migrate" value="1" class="scalable save">
            <span><span><span><?php echo $helper->__('Yes') ?></span></span></span>
        </button>
        <button title="<?php echo $helper->__('No') ?>" type="submit" name="migrate" value="0" class="scalable cancel">
            <span><span><span><?php echo $helper->__('No') ?></span></span></span>
        </button>
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
    </li>
</ul>