<script>
if (window.Meanbee === undefined) { window.Meanbee = {}; }
Meanbee.ShippingRules = Object.assign((Meanbee.ShippingRules || {}), {
  version: '<?php echo Mage::helper('meanbee_shippingrules/config')->getVersion() ?>',
  documentation: '<?php echo Mage::helper('meanbee_shippingrules/config')->getDocumentationURL() ?>',
  formKey: '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>',
  ajaxBasePath: '<?php echo Mage::getUrl('*/*/ajax'); ?>'
});
</script>
